---
- name: configure yum
  shell: |
          echo -e '[mongodb-org-3.4]\nname=MongoDB Repository\nbaseurl=https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/3.4/x86_64/\ngpgcheck=1\nenabled=1\ngpgkey=https://www.mongodb.org/static/pgp/server-3.4.asc' > /etc/yum.repos.d/mongodb-org-3.4.repo
  become: true
  become_user: root

- name: yum install mongodb
  shell: yum install -y mongodb-org
  become: true
  become_user: root

- name: start mongodb
  service:
          name: mongod
          state: started
  become: true
  become_user: root
